### ISSUE TITLE
앞으로 우리가 할 만한 백엔드의 과제 1. Event && DDD

### ISSUE THREAD

**Issue by JangAJang** [the-NDD/Gomterview-BE#21]
# 현재 우리 로직의 문제점
- Video, Question, Answer, Workbook의 경우에는 각 도메인이 다른 도메인의 리포지토리에 의존적인 문제가 발생한다. 
- 이러한 과정은 우리가 추가적인 기능을 구현할 때, 리펙토링할 때 생각보다 많은 디버깅 사항과 태스크 소요를 발생시킨다. 
    - 디버깅시에, 다른 도메인이 리펙토링 되는 경우가 빈번하다. 
    - A도메인의 리포지토리 기능 구현 => B도메인의 비즈니스 로직 구현의 방식으로 다른 도메인에 의존하게 된다.

# 이를 위해 DDD를 사용하면 어떨까?
- 각 도메인의 격리성을 향상시킬 수 있다. 
- 디버깅/리펙토링의 소요를 줄일 수 있다.

# 어떻게 구현해야할까?
## 코드 예시

`

    @Transactional()
    async createWorkbook(
      createWorkbookRequest: CreateWorkbookRequest,
      member: Member,
    ) {
      const category = await this.categoryRepository.findByCategoryId(
        createWorkbookRequest.categoryId,
      );
      validateManipulatedToken(member);
      validateCategory(category);
  
      const workbook = Workbook.of(
        createWorkbookRequest.title,
        createWorkbookRequest.content,
        category,
        member,
        createWorkbookRequest.isPublic,
      );
      const result = await this.workbookRepository.insert(workbook);
      return result.identifiers[0].id as number;
    }

`

- 해당 코드에서 validateManipulatedToken, validateCategory는 다른 도메인의 리포지토리를 이용한다. 
- 이런 부분을 각 도메인에서 일을 하게 한다. 
- WorkbookService는 WorkbookRepository만을 이용한다.

### Event를 이용하기
`
// workbook.service.ts

@Transactional()
  async createWorkbook(
    createWorkbookRequest: CreateWorkbookRequest,
    member: Member,
  ) {
    const category = await this.categoryRepository.findByCategoryId(
      createWorkbookRequest.categoryId,
    );
    this.eventEmitter.emit(
      ValidateCreateWorkbookEvent.EVENT_NAME,
      ValidateCreateWorkbookEvent.of(member, createWorkbookRequest.categoryId),
    );

    const workbook = Workbook.of(
      createWorkbookRequest.title,
      createWorkbookRequest.content,
      category,
      member,
      createWorkbookRequest.isPublic,
    );
    const result = await this.workbookRepository.insert(workbook);
    return result.identifiers[0].id as number;
  }

// category.service.ts
@OnEvent(ValidateCreateWorkbookEvent.EVENT_NAME, {async: true})
  async validateCategoryExistence(event: ValidateCreateWorkbookEvent) {
    const category = await this.categoryRepository.findByCategoryId(event.categoryId);
    if(!category) throw new CategoryNotFoundException();
  }
`
- 이런식으로 각 서비스에서 리포지토리를 분리할 수 있게 된다. 

# 생각해야 할 사항
- 현재 모든 로직을 트랜잭션화하려고 한다. 
  - 이를 위해, @Transactional을 라이브러리를 통해 활용하고 있다. 
  - 이벤트들을 같은 트랜잭션에 두기 위한 방안을 찾아보아야 한다. 
- [nest.js의 이벤트](https://docs.nestjs.com/techniques/events)에 대해 찾아보아야 한다.
- DDD의 디렉토리 구조 / 설계법등을 찾아보아야 한다. [원티드에서 진행하는 디자인 패턴 과제에서 해당 내용에 대해 정리해보았다.](https://github.com/JangAJang/wanted-preonboarding-challenge-backend-16/blob/master/studies/Jan23.md)

**Comment by quiet-honey** [comment]
DDD에 이러한 장점들이 있어서 많이 사용되는 것이었군요!! 깔끔하게 정리 잘 해주셔서 쉽게 이해할 수 있었습니다.
저 또한 DDD로 코드를 변경해나가는 것에 찬성합니다! 한 번 진행해보시죠! 저도 조그만한 부분부터 학습하면서 장희님 도와보겠습니다!

**Comment by JangAJang** [comment]
해당 pr은 조금 더 작은 단위로 쪼개서 올려보겠습니다! 아무래도 건드리는 코드의 양이 많아질 것 같습니다..ㅠ

**Comment by JangAJang** [comment]
진행상황
- [ ] 도메인 분리
    - [ ] Member
    - [ ] Category
    - [ ] Workbook
    - [ ] Question
    - [ ] Answer
    - [ ] Video

**Comment by JangAJang** [comment]
추가 고려해야 할 사항
- Member가 삭제되었을 때, Workbook&Answer&Video는 어떻게 처리할 것인가?
    - 도메인을 삭제할 것인가?
    - 도메인의 역정규화된 컬럼들을 null처리할 것인가?

**Comment by quiet-honey** [comment]
> 추가 고려해야 할 사항
> 
> * Member가 삭제되었을 때, Workbook&Answer&Video는 어떻게 처리할 것인가?
>   
>   * 도메인을 삭제할 것인가?
>   * 도메인의 역정규화된 컬럼들을 null처리할 것인가?

역정규화된 칼럼들을 null로 하더라도 어쨌든 비디오 등에 대한 정보는 남게 되는 상황인 것이죠? 개발 관점이 아닌 프라이버시 관점에서 봤을 때, 탈퇴한 회원의 정보를 특히 얼굴이 나오는 비디오를 서비스에서 그대로 가지고 있는 것은 피해야 하지 않을까라는 생각입니다!

**Comment by JangAJang** [comment]
onDeleteEvent로 만들어야 할 사항
- Member 삭제시
    - Workbook 삭제
    - Answer 삭제
    - Video null처리
- Workbook 삭제시
    - Question 삭제
- Question 삭제시
    - Answer 삭제
    - Video null처리
