### ISSUE TITLE
DDD 설정시 Dev의 DB 터짐 이슈

### ISSUE THREAD

**Issue by JangAJang** [the-NDD/Gomterview-BE#31]
## 터진거
- Video : Member, Question
- Workbook : Member.nickname, Member.profileImg
- Question : defaultAnswer.content
- Answer : [Member.id](http://member.id/), Member.nickname, Member.profileImg

## 이유
- Answer : memberId로 받아야 한다. questionId로 받아와야 한다.
- Question : 그냥 받아와야 함
- Video : memberId, questionId로 받아와야 한다.

**Comment by JangAJang** [comment]
또한, 해당 이슈를 생각해본 결과, 메인 서버를 마이그레이션하기 전에 Dev DB에 데이터들을 복사해두고, 해당 데이터들을 가져와 메인서버의 DB업데이트를 진행시켜야 할 것 같다는 생각이 듭니다. 

- 테이블의 구조 변경으로 데이터 조작이 조금 필요합니다. 
- 어떤 엔티티에서는 Member의 id를 memberId로, 어떤 곳에서는 member로 설정해두었습니다. 일치시켜야 할 필요가 있습니다.

**Comment by quiet-honey** [comment]
Production DB에서 도메인별 데이터의 수를 세어보았는데, Question은 약 500개, 나머지 도메인은 각각 100개 정도의 데이터가 있습니다. 대략 800개 정도 되는 셈이니 일일이 체크하면서 진행하기는 조금 어렵다고 생각이 되는데 말씀하신대로 자동화가 가능하다면 자동화 로직을 만들어서 진행하는게 더 빠르고, 정확성도 높을 것이라고 생각합니다!!
